### PR TITLE
Add Makie dependencies to precompile instructions

### PR DESCRIPTION
**Pull request by dlfivefifty**
I needed to add Makie dependencies to get precompilation to work. This updates the README.

### CODE REVIEW

**Comment by asinghvi17** [comment]
Hmm...those should get installed automatically, not sure what's going on there...

**Comment by dlfivefifty** [comment]
I get the following error:
```julia
  [c17dfb99] + WinRPM v0.4.2
[ Info: activating new environment at ~/.julia/packages/PackageCompiler/oT98U/packages/AbstractPlotting/Project.toml.
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
[ Info: used 430 out of 431 precompile statements
┌ Info: activating new environment at ~/.julia/packages/PackageCompiler/oT98U/packages/Project.toml.
└ @ Pkg.API /Users/solver/Projects/julia-1.1/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:519
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: LoadError: LoadError: ArgumentError: Package MakieGallery [dbd62bd0-c9f5-5087-a2e1-f5c4bb0cec90] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at ./loading.jl:929
 [2] require(::Base.PkgId) at ./loading.jl:858
 [3] require(::Module, ::Symbol) at ./loading.jl:853
 [4] include at ./boot.jl:326 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1038
 [6] include(::Module, ::String) at ./sysimg.jl:29
 [7] top-level scope at none:0
in expression starting at /Users/solver/.julia/packages/PackageCompiler/oT98U/packages/incremental_precompile.jl:17
in expression starting at /Users/solver/.julia/packages/PackageCompiler/oT98U/sysimg/run_julia_code.jl:10
ERROR: failed process: Process(`/Users/solver/Projects/julia-1.1/usr/bin/julia --optimize=3 --output-o=/Users/solver/.julia/packages/PackageCompiler/oT98U/sysimg/sys.a -g1 --track-allocation=none --startup-file=no --code-coverage=none --history-file=yes --inline=yes --math-mode=ieee --handle-signals=yes --warn-overwrite=no --compile=yes --depwarn=yes --cpu-target=native --track-allocation=none --sysimage-native-code=yes --sysimage=/Users/solver/Projects/julia-1.1/usr/lib/julia/sys.dylib -g1 --compiled-modules=yes --optimize=2 /Users/solver/.julia/packages/PackageCompiler/oT98U/sysimg/run_julia_code.jl`, ProcessExited(1)) [1]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at /Users/solver/Projects/julia-1.1/usr/lib/julia/sys.dylib:?
 [2] pipeline_error at ./process.jl:785 [inlined]
 [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
 [4] run at ./process.jl:724 [inlined]
 [5] #run_julia#1 at /Users/solver/.julia/packages/PackageCompiler/oT98U/src/compiler_flags.jl:225 [inlined]
 [6] #run_julia at ./none:0 [inlined]
 [7] #compile_incremental#62(::Bool, ::Bool, ::Bool, ::Nothing, ::Function, ::String, ::String) at /Users/solver/.julia/packages/PackageCompiler/oT98U/src/incremental.jl:82
 [8] #compile_incremental#63 at ./none:0 [inlined]
 [9] (::getfield(PackageCompiler, Symbol("#kw##compile_incremental")))(::NamedTuple{(:force,),Tuple{Bool}}, ::typeof(compile_incremental), ::Symbol, ::Symbol) at ./none:0
 [10] top-level scope at none:0
```

**Comment by asinghvi17** [comment]
Hmm....that might be the result of some changes to the package manager which we may not have accounted for, I'll check up on that.  The switch from `REQUIRE` to `Project.toml` has a had a couple of side effects...

**Comment by asinghvi17** [comment]
@dlfivefifty, is the precompile issue you were getting fixed with the new release?

**Comment by asinghvi17** [comment]
Closing in favour of #364

**Pull request closed without merging**
