### PR TITLE
allow RGB inputs for heatmap

### LINKED ISSUE #2033: Error while rendering a heatmap with RGB z-matrix
If I replace GLMakie by CairoMakie, the plot is rendered without problems:

```julia
julia> using Meshes, MeshViz

julia> import GLMakie as Mke

julia> g = CartesianGrid(10, 10)
10×10 CartesianGrid{2,Float64}
  minimum: Point(0.0, 0.0)
  maximum: Point(10.0, 10.0)
  spacing: (1.0, 1.0)

julia> viz(g, color = 1:100)

┌ Error: Error while rendering!
│   exception =
│    MethodError: no method matching gluniform(::Int32, ::Nothing)
│    Closest candidates are:
│      gluniform(::Integer, ::Union{ColorTypes.Colorant, StaticArrays.SMatrix, StaticArrays.StaticVector}) at ~/.julia/packages/GLMakie/vwLnZ/src/GLAbstraction/GLUniforms.jl:36
│      gluniform(::Integer, ::Enum) at ~/.julia/packages/GLMakie/vwLnZ/src/GLAbstraction/GLUniforms.jl:71
│      gluniform(::Integer, ::Observables.Observable{T}) where T at ~/.julia/packages/GLMakie/vwLnZ/src/GLAbstraction/GLUniforms.jl:73
│      ...
└ @ GLMakie ~/.julia/packages/GLMakie/vwLnZ/src/rendering.jl:242
```

### PR DESCRIPTION
**Pull request by ffreyer**
# Description

Fixes #2033

Adds support for `heatmap(xs, ys, img)` (back?)

## Type of change

New feature / Bug fix

## Checklist

- [x] Added an entry in NEWS.md (for new features and breaking changes)
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

### CODE REVIEW

**Comment by juliohm** [comment]
Can this PR be merged?

**Comment by ffreyer** [comment]
Yes, it's ready to be merged. I just need someone to review it

**Comment by juliohm** [comment]
@SimonDanisch can you please take a look at this PR?

**Comment by juliohm** [comment]
This PR contains a hot fix for an important issue. Appreciate if someone can review it.

Thank you again @ffreyer for the quick fix.

**Pull request merged**
