### PR TITLE
remove static arrays

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Funny, didn't think this would pass :D 
This needs https://github.com/JuliaGeometry/GeometryBasics.jl/pull/169 to fully remove staticarrays, but since this seems to be non breaking, we could also merge this before tagging https://github.com/JuliaGeometry/GeometryBasics.jl/pull/169. 
Definitely a nice simplification of used types on its own.
The above plot is from running the benchmarks locally on julia 1.9 with https://github.com/JuliaGeometry/GeometryBasics.jl/pull/169 checked out.

**Comment by SimonDanisch** [comment]
CI is a bit noisy and doesn't use the GeometryBasics branch, so I run the compile benchmark locally on julia master with all the right packages checked out.
Preserving this here for when CI overwrites the current plot:
image

**Comment by oscardssmith** [comment]
Is this time difference changed by https://github.com/JuliaLang/julia/pull/43990?

**Comment by SimonDanisch** [comment]
Both already use https://github.com/JuliaLang/julia/pull/43990?

**Pull request merged**
