### PR TITLE
Update makie_logo_transparent.svg

### PR DESCRIPTION
**Pull request by cormullion**
# Description

The text "Makie" is invisible if you use Github in Dark Mode. The simplest fix is to add a thin white stroke. Better would be to add a slight border on the original. Or to make a non-transparent image that has some cool background elements!

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
Ah yes that makes sense, I don't think Github allows to have css-dependent images in a Readme so maybe the banner-like solution could also work.

**Comment by jkrumbiegel** [comment]
I'll merge this for a quick fix and we can think about a different solution when we have time :) thanks!

**Comment by cormullion** [comment]
Haha, I'm stupid - I edited the wrong one...I should have changed the "canvas" one : 

Screenshot 2022-05-24 at 15 18 22

Never mind, it will keep for another day! :)

**Comment by jkrumbiegel** [comment]
Yeah I noticed that too after merging ;)

**Pull request merged**
