### PR TITLE
Add projection `space` option as a generic attribute

### LINKED ISSUE #994: `scatter` + `Axis3` + `GLMakie` does not work
This came up in slack:
```julia
f = Figure()
pos = rand(Point3f0, 10)
ax3 = f[1,1] = Axis3(f)
scatter!(ax3, pos)
lines!(ax3, pos)
```
The points do not show up in `GLMakie`:
Screenshot 2021-05-27 at 11 51 17
as they do with `CairoMakie`
Screenshot 2021-05-27 at 11 52 19

~~This seems do be independent of the `markersize` argument.~~

### LINKED ISSUE #1472: [FR] Plotting text in "axis coordinates"
Hi, 
MWE:
image

In the bottom left corner of each axis I want to plot "s = ..." where s is the slope of the red line. It becomes unpleasant to specify the location of this text in data coordinates. I would like to specify it in "axis coordinates".

This means: I give location = (0.1, 0.1) and this plots the text in the 10% x and 10%y location of the axis. Does this make sense? In PyPlot I do this by providing a transformation, not sure if it is possible in makie. If not, consider this a feature request instead of docs. If it is possible, then please add this info here: https://makie.juliaplots.org/stable/examples/plotting_functions/text/index.html or just tell me so I do the PR.

### LINKED ISSUE #1602: Text not rendered correctly with 3d orthographic camera
I cannot understand the behavior of `near` and `far` planes for 3d orthographic camera in case of text:

```julia
using GLMakie
using GeometryBasics

scene = Scene()

mesh!(scene, FRect3D(Vec3f0(-15,-10,0), Vec3f0(30,20,5)), color = :blue)
p = poly!(scene, Rect2D(-5,-5,10,10), color = :red)
translate!(p, Vec3f0(0,0,10))
text!(scene, ". HELLO", position = Vec3f0(0,0,15))

cam = cam3d!(scene)
cam.attributes.projectiontype[] = Makie.Orthographic
# cam.attributes.projectiontype[] = Makie.Perspective #OK
center!(scene)
cam.attributes.fixed_axis[] = false
cam.eyeposition[] = Vec3f0(0, 0, 100)
cam.lookat[] = Vec3f0(0, 0, 0) 
cam.upvector[] = Vec3f0(0, 1, 0)

cam.near[] = 1
cam.far[] = 1000

update_cam!(scene, cam)
scene
```

The script above should set the camera of the following scene

as "top view", perpendicular to XY plane:

Text is not rendered correctly even if camera settings should be ok:
- mesh Z crd: 0-5
- poly Z crd: 10
- text Z crd: 15
- eyeposition Z crd: 100
- near camera plane = 1
- far camera plane = 1000

Moreover, by setting:
- `cam.far` >190 text is hidden (?), mesh and poly visible [but everything is fine with Perspective projection]
- 95< `cam.far` <190 text, mesh and poly are visible (expected)
- 90< `cam.far` <95 text and poly are visible (expected)
- 90< `cam.far` <85 text only is visible (expected)
- 85< `cam.far` <1 text is still visible (?)

GLMakie v0.5.0
Makie v0.16.1

### PR DESCRIPTION
**Pull request by ffreyer**
# Description

This pr adds `space` as a general attribute to switch between camera space, pixel space, unit space (0..1) and maybe clip space (-1..1). That way you can adjust the units of the plot without creating another scene or messing with camera matrices.

Currently works in GLMakie:

```julia
using GLMakie
fig = Figure()
# ax = LScene(fig[1, 1])
# ax = Axis(fig[1, 1])
ax = Axis3(fig[1, 1])
meshscatter!(ax, Point3f.(1:10, 1:10, 1:10), space = :data, color = :blue)
# scatter!(ax, Point2f.(1:10, 1:10), space = :data, color = :blue)
scatter!(ax, Point2f.(200, 100:100:500), space = :pixel, color = :red)
scatter!(ax, Point2f.(0.6, 0.1:0.1:0.9), space = :relative, color = :green)
scatter!(ax, Point2f.(0.9, -0.9:0.2:0.9), space = :clip, color = :orange)
display(fig)
```

Screenshot from 2022-01-15 14-46-11

## Type of change

Breaking change because the `space` attribute in `text` has been renamed to `markerspace` and `space` now means something else.

## Checklist

- [x] Added an entry in NEWS.md (for new features and breaking changes)
- [x] Added or changed relevant sections in the documentation
- [x] Added unit tests for new algorithms, conversion methods, etc.
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.
- [x] Works in GLMakie
- [x] Works in CairoMakie
- [x] Works in WGLMakie
- ~~Works in RPRMakie~~ I don't know how to make it work
- [x] Works with nested plots
- [x] Works with mixed `markerspace` in all combinations (scatter, text)
- [x] pass space through ~~everything~~ poly - I think for most recipes there isn't really a point in adding `space` as an attribute

## Related issues

- fixes #994 (somehow)
- fixes #1602 (probably because I switched away from `project`?)
- closes #1472 
- implements "display", "figure/scene/axis" and "data" coordinates from #369

### CODE REVIEW

**Comment by ffreyer** [comment]
I think I got all combinations of space and markerspace to work with text now
```julia
fig = Figure(resolution = (700, 700))
ax = Axis(fig[1, 1], width = 600, height = 600)
spaces = (:data, :pixel, :relative, :clip)
xs = [
    [0.1, 0.35, 0.6, 0.85], 
    [0.1, 0.35, 0.6, 0.85] * 600,
    [0.1, 0.35, 0.6, 0.85],
    2 .* [0.1, 0.35, 0.6, 0.85] .- 1
]
for (i, space) in enumerate(spaces)
    for (mspace, j, scale) in zip(spaces, 1:4, (0.02, 10, 0.02, 0.04))
        text!(
            ax, "$space\n$mspace", position = Point2f(xs[i][i], xs[i][j]), 
            textsize = scale, space = space, markerspace = mspace
        )
    end
end
xlims!(ax, 0, 1)
ylims!(ax, 0, 1)
fig
```
Screenshot from 2022-01-16 20-42-35

**Comment by ffreyer** [comment]
The depth shift test should fail here because I changed some things back to how they were when the test was added:
1. I removed the axes. It seems like the `scenekw=(show_axis = false,)` didn't get adjusted with the scene rework.
2. I added an explicit `center!`. It seems like that used to run after `translate!` and `scale!` before, but not anymore.

**Comment by ffreyer** [comment]
I checked a bunch of the lower scoring tests. In GLMakie:
- "Depth Shift" is fine, see above
- "Streamplot animation" seems fine
- "image scatter" is a 3D scatter plot with screenspace markers so it's scaling got changed
- "Text rotation" looks exactly the same as the refimage to me?
- "3D Contour with 2d countour slices" looks different because it's from before #1559 
- "3D screenspace annotations" hides part of the text inside the scattered spheres which is technically correct but differs from before

I also checked a few of the worst cases in CairoMakie. Most of them are just 3D plots

**Comment by ffreyer** [comment]
#1632 moves the the preprojection math into shaders in GLMakie and WGLMakie. I kept it separate to make it a bit easier to review (though it ended up being very little work in shaders)

**Comment by ffreyer** [comment]
Tests are still fine

**Comment by ffreyer** [comment]
Another TODO:
- [ ] scatter with FastPixel currently doesn't have camera matrices attached in GLMakie

**Comment by SimonDanisch** [comment]
and:
- [ ] fix text offset
text-off2

**Comment by ffreyer** [comment]
I checked a couple of rectangles in the example above. Seems like it's generally a bit better centered after the pr. Before the offsets of the centers of text bounding boxes to centers of heatmap rectangles at the corners are
```
(1, 0.5) ... (0.5, 0.5)
   :              :
(1, 1.5) ... (0.5, 1.5)
```
pixel and after it's (-0.5, +0.5) with some rectangle inside being (-0.5, +0.5). I'd say it's better now.

**Comment by SimonDanisch** [comment]
Ok, I fixed the `FastPixel` marker. I tried uploading the new reference images, but it currently doesnt work :( 
I'll merge this nevertheless, to finally be able to merge all these other PRs that have merge conflict with this one. We can update the reference images later.

**Comment by simonbyrne** [comment]
This appears to have broken GeoMakie:

```
julia> fig = Figure()

julia> ax = GeoAxis(fig[1,1]; dest = "+proj=wintri")
ERROR: Space screen not recognized. Must be one of (:data, :pixel, :relative, :clip)
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] space_to_clip
    @ ~/.julia/dev/Makie/src/camera/projection_math.jl:324 [inlined]
  [3] space_to_clip
    @ ~/.julia/dev/Makie/src/camera/projection_math.jl:315 [inlined]
  [4] (::GLMakie.var"#143#154"{Camera})(s::Symbol, ms::Symbol, pv::StaticArrays.SMatrix{4, 4, Float32, 16}, res::Vec{2, Float32})
    @ GLMakie ~/.julia/dev/Makie/GLMakie/src/drawing_primitives.jl:384
  [5] map(::GLMakie.var"#143#154"{Camera}, ::Observable{Symbol}, ::Observable{Symbol}, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Observables ~/.julia/packages/Observables/OFj0u/src/Observables.jl:477
  [6] map(::GLMakie.var"#143#154"{Camera}, ::Observable{Symbol}, ::Observable{Symbol}, ::Observable{StaticArrays.SMatrix{4, 4, Float32, 16}}, ::Vararg{Any})
    @ Observables ~/.julia/packages/Observables/OFj0u/src/Observables.jl:466
  [7] (::GLMakie.var"#133#144"{Scene, MakieCore.Text{Tuple{Makie.GlyphCollection}}})(gl_attributes::Dict{Symbol, Any})
    @ GLMakie ~/.julia/dev/Makie/GLMakie/src/drawing_primitives.jl:383
  [8] (::GLMakie.var"#103#106"{GLMakie.var"#133#144"{Scene, MakieCore.Text{Tuple{Makie.GlyphCollection}}}, GLMakie.Screen, Scene, MakieCore.Text{Tuple{Makie.GlyphCollection}}})()
    @ GLMakie ~/.julia/dev/Makie/GLMakie/src/drawing_primitives.jl:107
  [9] get!(default::GLMakie.var"#103#106"{GLMakie.var"#133#144"{Scene, MakieCore.Text{Tuple{Makie.GlyphCollection}}}, GLMakie.Screen, Scene, MakieCore.Text{Tuple{Makie.GlyphCollection}}}, h::Dict{UInt64, GLMakie.GLAbstraction.RenderObject}, key::UInt64)
    @ Base ./dict.jl:464
 [10] cached_robj!(robj_func::GLMakie.var"#133#144"{Scene, MakieCore.Text{Tuple{Makie.GlyphCollection}}}, screen::GLMakie.Screen, scene::Scene, x::MakieCore.Text{Tuple{Makie.GlyphCollection}})
    @ GLMakie ~/.julia/dev/Makie/GLMakie/src/drawing_primitives.jl:85
 [11] draw_atomic
    @ ~/.julia/dev/Makie/GLMakie/src/drawing_primitives.jl:304 [inlined]
 [12] insert!
    @ ~/.julia/dev/Makie/GLMakie/src/drawing_primitives.jl:121 [inlined]
 [13] (::GLMakie.var"#109#110"{GLMakie.Screen, Scene})(x::MakieCore.Text{Tuple{Makie.GlyphCollection}})
    @ GLMakie ~/.julia/dev/Makie/GLMakie/src/drawing_primitives.jl:126
 [14] foreach(f::GLMakie.var"#109#110"{GLMakie.Screen, Scene}, itr::Vector{AbstractPlot})
    @ Base ./abstractarray.jl:2694
 [15] insert!(screen::GLMakie.Screen, scene::Scene, x::Combined)
    @ GLMakie ~/.julia/dev/Makie/GLMakie/src/drawing_primitives.jl:123
 [16] push!(scene::Scene, plot::MakieCore.Text{Tuple{String}})
    @ Makie ~/.julia/dev/Makie/src/scenes.jl:368
 [17] plot!(scene::Scene, P::Type{MakieCore.Text{Tuple{String}}}, attributes::Attributes, input::Tuple{Observable{Any}}, args::Observable{Tuple{String}})
    @ Makie ~/.julia/dev/Makie/src/interfaces.jl:403
 [18] plot!(scene::Scene, P::Type{MakieCore.Text}, attributes::Attributes, args::Observable{Any}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/dev/Makie/src/interfaces.jl:320
 [19] plot!
    @ ~/.julia/dev/Makie/src/interfaces.jl:288 [inlined]
 [20] #plot!#145
    @ ~/.julia/dev/Makie/src/interfaces.jl:271 [inlined]
 [21] text!(::Scene, ::Vararg{Any}; attributes::Base.Pairs{Symbol, Any, NTuple{9, Symbol}, NamedTuple{(:textsize, :color, :position, :visible, :align, :rotation, :font, :markerspace, :inspectable), Tuple{Observable{Any}, Observable{Any}, Observable{Point{2, Float32}}, Observable{Any}, Observable{Tuple{Symbol, Symbol}}, Observable{Float32}, Observable{Any}, Symbol, Bool}}})
    @ MakieCore ~/.julia/packages/MakieCore/A0hGm/src/recipes.jl:37
 [22] Makie.MakieLayout.LineAxis(parent::Scene; kwargs::Base.Pairs{Symbol, Observable, NTuple{36, Symbol}, NamedTuple{(:endpoints, :limits, :flipped, :ticklabelrotation, :ticklabelalign, :labelsize, :labelpadding, :ticklabelpad, :labelvisible, :label, :labelfont, :ticklabelfont, :ticklabelcolor, :labelcolor, :tickalign, :ticklabelspace, :ticks, :tickformat, :ticklabelsvisible, :ticksvisible, :spinevisible, :spinecolor, :spinewidth, :ticklabelsize, :trimspine, :ticksize, :reversed, :tickwidth, :tickcolor, :minorticksvisible, :minortickalign, :minorticksize, :minortickwidth, :minortickcolor, :minorticks, :scale), Tuple{Observable{Tuple{Point{2, Float32}, Point{2, Float32}}}, Observable{Tuple{Float32, Float32}}, Observable{Bool}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Bool}, Observable{Symbol}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}, Observable{Any}}}})
    @ Makie.MakieLayout ~/.julia/dev/Makie/src/makielayout/lineaxis.jl:174
 [23] layoutable(::Type{Axis}, fig_or_scene::Figure; bbox::Nothing, kwargs::Base.Pairs{Symbol, Any, NTuple{4, Symbol}, NamedTuple{(:aspect, :xticks, :yticks, :limits), Tuple{DataAspect, Tuple{Vector{Float32}, Vector{String}}, Tuple{Vector{Float32}, Vector{String}}, Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}}}}})
    @ Makie.MakieLayout ~/.julia/dev/Makie/src/makielayout/layoutables/axis.jl:208
 [24] #_layoutable#11
    @ ~/.julia/dev/Makie/src/makielayout/layoutables.jl:69 [inlined]
 [25] _layoutable(::Type{Axis}, ::GridPosition; kwargs::Base.Pairs{Symbol, Any, NTuple{4, Symbol}, NamedTuple{(:aspect, :xticks, :yticks, :limits), Tuple{DataAspect, Tuple{Vector{Float32}, Vector{String}}, Tuple{Vector{Float32}, Vector{String}}, Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}}}}})
    @ Makie.MakieLayout ~/.julia/dev/Makie/src/makielayout/layoutables.jl:64
 [26] #_#9
    @ ~/.julia/dev/Makie/src/makielayout/layoutables.jl:49 [inlined]
 [27] GeoAxis(args::GridPosition; source::String, dest::String, transformation::Proj4.Transformation, lonticks::StepRange{Int64, Int64}, latticks::StepRange{Int64, Int64}, hidespines::Bool, coastlines::Bool, coastline_attributes::NamedTuple{(), Tuple{}}, aspect::DataAspect, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ GeoMakie ~/.julia/dev/GeoMakie/src/geoaxis.jl:74
 [28] top-level scope
    @ REPL[7]:1
```

**Comment by simonbyrne** [comment]
Ah, nevermind, I hadn't dev-ed MakieCore.

**Pull request merged**
