### PR TITLE
Paper for JOSS

### PR DESCRIPTION
**Pull request by asinghvi17**
This is currently in a very WIP state, but I wanted to at least get it started so we can build up some momentum before Vizcon.  

From the JOSS docs, we need to have these things:

- [ ] A list of the authors of the software and their affiliations, using the correct format.
- [ ] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- [ ] A clear Statement of Need that illustrates the research purpose of the software.
- [ ] A list of key references, including to other software addressing related needs.
- [ ] Mention (if applicable) of any past or ongoing research projects using the software and recent scholarly publications enabled by it.
- [ ] Acknowledgement of any financial support.

### CODE REVIEW

**Comment by asinghvi17** [comment]
This is what the paper looks like now, BTW:
[paper.pdf](https://github.com/JuliaPlots/Makie.jl/files/4208970/vrj5jdakswyzadt60nms.pdf)

CCing people from https://github.com/JuliaPlots/Makie.jl/issues/428 in here:

@kescobo @mkborregaard @SimonDanisch @jkrumbiegel @Datseris @Kevin-Mattheus-Moerman

**Comment by Datseris** [comment]
I need to be detached from this if you ask for me to be a reviewer, so I'll go ahead and unsubscribe from this post :)

**Comment by asinghvi17** [comment]
Fair enough, I just blanket pinged everyone in the thread anyway :D.  There's no content in this as of now.

**Comment by kescobo** [comment]
Please feel free to use my figure - I'd only ask that you cite https://doi.org/10.1101/2020.02.13.944181 (if it gets peer reviewed and published elsewhere, I'll add that citation). 
One thought though - @mkborregaard was suggesting possibly multiple papers, including a separate one for MakieLayout, in which case my figure fit better there.

I'd be happy to help with writing etc too, though would want to talk about being included as an author before getting too heavily involved. That said, I actually don't think I'd be of much use on that front, as all I did was ask @jkrumbiegel for help and do what he told me :laugh:. I'm perfectly happy to do some rounds of review / comment once there's more content without expecting author credit.

**Pull request closed without merging**
