### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by asinghvi17**
Updates Project.toml with autogenerated file from REQUIRE.  Uses Stefan Karpinski's `gen-project.jl` in Pkg.jl.

Directly fixes #339.

Let's see if the tests work :)

### CODE REVIEW

**Comment by asinghvi17** [comment]
CI failed because of an old GLMakie bug?  Odd...

```julia
running linesegments___colors
1   : #version 330
2   : 
3   : #extension GL_ARB_conservative_depth: enable
4   : 
5   : in vec2 vertex;
6   : in vec3 color;
7   : uniform float thickness;
8   : 
9   : uniform mat4 projection, view, model;
10  : uniform uint objectid;
11  : 
12  : out uvec2 g_id;
13  : out vec4 g_color;
14  : out float g_thickness;
15  : 
16  : vec4 getindex(sampler2D tex, int index);
17  : vec4 getindex(sampler1D tex, int index);
18  : 
19  : vec4 to_vec4(vec3 v){return vec4(v, 1);}
20  : vec4 to_vec4(vec2 v){return vec4(v, 0, 1);}
21  : 
22  : 
23  : void main()
24  : {
25  :     int index   = gl_VertexID;
26  :     g_id        = uvec2(objectid, index+1);
27  :     g_color     = color;;
28  :     g_thickness = thickness;
29  :     gl_Position = projection*view*model*to_vec4(vertex);
30  : }
31  : 
┌ Warning: shader /builds/JuliaGPU/Makie.jl/.julia/packages/GLMakie/nDrlO/src/GLVisualize/assets/shader/line_segment.vert didn't compile. 
│ 0(27) : error C1035: assignment of incompatible types
└ @ GLMakie.GLAbstraction /builds/JuliaGPU/Makie.jl/.julia/packages/GLMakie/nDrlO/src/GLAbstraction/GLShader.jl:142
ERROR: LoadError: program 81 not linked. Error in: 
/builds/JuliaGPU/Makie.jl/.julia/packages/GLMakie/nDrlO/src/GLVisualize/assets/shader/fragment_output.frag or /builds/JuliaGPU/Makie.jl/.julia/packages/GLMakie/nDrlO/src/GLVisualize/assets/shader/util.vert or /builds/JuliaGPU/Makie.jl/.julia/packages/GLMakie/nDrlO/src/GLVisualize/assets/shader/line_segment.vert or /builds/JuliaGPU/Makie.jl/.julia/packages/GLMakie/nDrlO/src/GLVisualize/assets/shader/line_segment.geom or /builds/JuliaGPU/Makie.jl/.julia/packages/GLMakie/nDrlO/src/GLVisualize/assets/shader/lines.frag
Vertex info
-----------
0(27) : error C1035: assignment of incompatible types
(0) : error C2003: incompatible options for link
```

**Comment by SimonDanisch** [comment]
Looks good... I guess we should test this locally?!

**Comment by asinghvi17** [comment]
Tests on my machine fail for a completely different reason - LibCURL sporadically fails, but it constantly fails on WorldClim.  

Here's the error:

```julia
ERROR: LoadError: LoadError: failed process: Process(`curl -g -L -f -o prec.zip http://biogeo.ucdavis.edu/data/worldclim/v2.0/tif/base/wc2.0_10m_prec.zip`, ProcessExited(48)) [48]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
 [2] pipeline_error at ./process.jl:785 [inlined]
 [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
 [4] run at ./process.jl:724 [inlined]
 [5] download(::String, ::String) at ./download.jl:27
 [6] load_dataset(::String) at ./worldclim_visualization:56
 [...]
in expression starting at worldclim_visualization:67
in expression starting at /Users/anshul/.julia/dev/Makie/test/runtests.jl:12
ERROR: Package Makie errored during testing
```
This is something that I'll probably have to debug manually in LibCURL - but the packages load, at least.

**Comment by SimonDanisch** [comment]
I thought I fixed that error -.-

**Comment by SimonDanisch** [comment]
https://github.com/JuliaPlots/MakieGallery.jl/blob/master/examples/bigdata.jl#L57
Setting LD_LIBRARY_PATH here to "" was supposed to fix curl errors.... GDAL puts julia libdir into LD_LIBRARY_PATH, which in turn makes `download` use julia's curl, which is compiled without correct certificates ... Or something like that :P

**Comment by asinghvi17** [comment]
Waiting on Gitlab CI now - if that works, then this should be good to merge?

**Comment by asinghvi17** [comment]
After this merge, JuliaPlots/MakieGallery.jl#47 and JuliaPlots/MakieGallery.jl#51, should we tag new versions of Makie and MakieGallery?  47 should just change the Project.toml file to fix ImageCore incompatibilities, and 51 fixes the tests with minimal as default, but full on PRs.

**Comment by edljk** [comment]
`Cylinder` type may be easily adapted to create a cone type.

**Pull request merged**
