### PR TITLE
Switch to GeometryBasics 0.4.1

### PR DESCRIPTION
**Pull request by devmotion**
This is an updated version of https://github.com/JuliaPlots/Makie.jl/pull/1132. I reran the script (https://github.com/JuliaGeometry/GeometryBasics.jl/pull/97#issue-497319718) and added the deprecation warnings for `Quaternionf0`, `RGBf0`, and `RGBAf0` from the previous PR.

### CODE REVIEW

**Comment by devmotion** [comment]
@SimonDanisch I think this PR is ready for review :slightly_smiling_face: 

As in the previous PR, I reexported the deprecated bindings from GLMakie etc. to avoid a breaking change. Unfortunately, this leads to deprecations warnings such as https://github.com/JuliaPlots/Makie.jl/pull/1252/checks?check_run_id=3402333581#step:7:195 in the tests. However, users should not notice it since they won't see the warnings :shrug:

**Comment by SimonDanisch** [comment]
Awesome :) I think we should re-export the old names with a depwarn?

**Comment by devmotion** [comment]
Ah yeah, so far only the names defined in Makie were deprecated and these deprecations were reexported by CairoMakie etc. In the last commit I also reexported the deprecated bindings from GeometryBasics in Makie, so `Vec3f0` etc. should be still available if one loads Makie but show a deprecation warning (if warnings are enabled). And they should be reexported by CairoMakie etc. automatically.

**Comment by devmotion** [comment]
I just checked with `julia --depwarn=yes`, and it seems to work :smile: 
```julia
julia> using GLMakie
[ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]
WARNING: importing deprecated binding GeometryBasics.FRect into Makie.
WARNING: GeometryBasics.FRect is deprecated, use Rectf instead.
  likely near none:1
WARNING: importing deprecated binding Makie.FRect into GLMakie.
WARNING: importing deprecated binding GeometryBasics.FRect2D into Makie.
WARNING: GeometryBasics.FRect2D is deprecated, use Rect2f instead.
  likely near none:1
WARNING: importing deprecated binding Makie.FRect2D into GLMakie.
WARNING: importing deprecated binding GeometryBasics.FRect3D into Makie.
WARNING: GeometryBasics.FRect3D is deprecated, use Rect3f instead.
  likely near none:1
WARNING: importing deprecated binding Makie.FRect3D into GLMakie.
WARNING: importing deprecated binding GeometryBasics.IRect into Makie.
WARNING: GeometryBasics.IRect is deprecated, use Recti instead.
  likely near none:1
WARNING: importing deprecated binding Makie.IRect into GLMakie.
WARNING: importing deprecated binding GeometryBasics.IRect2D into Makie.
WARNING: GeometryBasics.IRect2D is deprecated, use Rect2i instead.
  likely near none:1
WARNING: importing deprecated binding Makie.IRect2D into GLMakie.
WARNING: importing deprecated binding GeometryBasics.IRect3D into Makie.
WARNING: GeometryBasics.IRect3D is deprecated, use Rect3i instead.
  likely near none:1
WARNING: importing deprecated binding Makie.IRect3D into GLMakie.
WARNING: importing deprecated binding GeometryBasics.Point2f0 into Makie.
WARNING: GeometryBasics.Point2f0 is deprecated, use Point2f instead.
  likely near none:1
WARNING: importing deprecated binding Makie.Point2f0 into GLMakie.
WARNING: importing deprecated binding GeometryBasics.Point3f0 into Makie.
WARNING: GeometryBasics.Point3f0 is deprecated, use Point3f instead.
  likely near none:1
WARNING: importing deprecated binding Makie.Point3f0 into GLMakie.
WARNING: importing deprecated binding GeometryBasics.Point4f0 into Makie.
WARNING: GeometryBasics.Point4f0 is deprecated, use Point4f instead.
  likely near none:1
WARNING: importing deprecated binding Makie.Point4f0 into GLMakie.
WARNING: Makie.Quaternionf0 is deprecated, use Quaternionf instead.
  likely near none:1
WARNING: importing deprecated binding Makie.Quaternionf0 into GLMakie.
WARNING: Makie.RGBAf0 is deprecated, use RGBAf instead.
  likely near none:1
WARNING: importing deprecated binding Makie.RGBAf0 into GLMakie.
WARNING: Makie.RGBf0 is deprecated, use RGBf instead.
  likely near none:1
WARNING: importing deprecated binding Makie.RGBf0 into GLMakie.
WARNING: importing deprecated binding GeometryBasics.Rect2D into Makie.
WARNING: GeometryBasics.Rect2D is deprecated, use Rect2 instead.
  likely near none:1
WARNING: importing deprecated binding Makie.Rect2D into GLMakie.
WARNING: importing deprecated binding GeometryBasics.Rect3D into Makie.
WARNING: GeometryBasics.Rect3D is deprecated, use Rect3 instead.
  likely near none:1
WARNING: importing deprecated binding Makie.Rect3D into GLMakie.
WARNING: importing deprecated binding GeometryBasics.Vec2f0 into Makie.
WARNING: GeometryBasics.Vec2f0 is deprecated, use Vec2f instead.
  likely near none:1
WARNING: importing deprecated binding Makie.Vec2f0 into GLMakie.
WARNING: importing deprecated binding GeometryBasics.Vec3f0 into Makie.
WARNING: GeometryBasics.Vec3f0 is deprecated, use Vec3f instead.
  likely near none:1
WARNING: importing deprecated binding Makie.Vec3f0 into GLMakie.
WARNING: importing deprecated binding GeometryBasics.Vec4f0 into Makie.
WARNING: GeometryBasics.Vec4f0 is deprecated, use Vec4f instead.
  likely near none:1
WARNING: importing deprecated binding Makie.Vec4f0 into GLMakie.

julia> Vec3f0
WARNING: GeometryBasics.Vec3f0 is deprecated, use Vec3f instead.
  likely near REPL[3]:1
Vec{3, Float32}
```

**Comment by SimonDanisch** [comment]
Alright lets do this!!!

**Pull request merged**
