### PR TITLE
Fix automatically generated normals

### PR DESCRIPTION
**Pull request by jkrumbiegel**
grafik

### CODE REVIEW

**Comment by SimonDanisch** [comment]
We should also fix that no normals are generated as default... That was always intended, but I think it has been bitrotting!

**Comment by jkrumbiegel** [comment]
So not merge this?

**Comment by SimonDanisch** [comment]
Hm the example is nice & the comment about order dependence...
But would be nice to fix the normal generation as well... Can take a look tomorrow!

**Review by SimonDanisch — APPROVED** [review]

**Comment by SimonDanisch** [comment]
Ok, the example didn't make that much sense anymore, after fixing the automatic normal generation.
I removed it for now, and hope to add it back better later!

**Pull request merged**
