### PR TITLE
Update volumeslices - docs

### PR DESCRIPTION
**Pull request by t-bltg**
vol-slices

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Cool, thank you! :)  
This was just a random recipe that I added at some point, but I guess it's a useful enough for us to maintain it :) 

image
This actually looks wrong - those circles should line up...

**Comment by t-bltg** [comment]
> This was just a random recipe that I added at some point, but I guess it's a useful enough for us to maintain it :)
I think this is pretty useful for visualizing volumetric data :)

> This actually looks wrong - those circles should line up...
```julia
x = LinRange(0, π, 50)
y = LinRange(0, 2π, 100)
z = LinRange(0, 3π, 150)
vol = [cos(X)*sin(Y)*sin(Z) for X ∈ x, Y ∈ y, Z ∈ z]
```
That does seem right to me, doesn't it ?

**Comment by SimonDanisch** [comment]
The input isn't wrong, the planes are flipped ;)

**Comment by t-bltg** [comment]
> The input isn't wrong, the planes are flipped ;)

That still looks right to me, compared to:
```julia
using GLMakie

main() = begin
  fig = Figure(); axes = [Axis(fig[i, 1]) for i ∈ 1:3]

  x = LinRange(0, π, 50)
  y = LinRange(0, 2π, 100)
  z = LinRange(0, 3π, 150)
  v = [cos(X)*sin(Y)*sin(Z) for X ∈ x, Y ∈ y, Z ∈ z]

  ax = axes[1, 1]
  heatmap!(ax, y, z, v[length(x)÷2, :, :])
  ax.aspect = DataAspect()
  ax.title = "yz plane - x axis"
  ax.xlabel = "y"
  ax.ylabel = "z"
  ax = axes[2, 1]
  heatmap!(ax, x, z, v[:, length(y)÷2, :])
  ax.aspect = DataAspect()
  ax.title = "xz plane - y axis"
  ax.xlabel = "x"
  ax.ylabel = "z"
  ax = axes[3, 1]
  heatmap!(ax, x, y, v[:, :, length(z)÷2])
  ax.aspect = DataAspect()
  ax.title = "xy plane - z axis"
  ax.xlabel = "x"
  ax.ylabel = "y"

  save("heatmap.png", fig)
  return
end

main()
```
heatmap

With the `show_axis=true`:
volslices

**Comment by SimonDanisch** [comment]
Where the planes meet, they need to go through the same points in the volume, so they need to have have the same color where they meet... That's quite clearly not happening:
image
That happens either because they're flipped, or because the colorrange is different, so the color gets mapped differently.
The colorrange should actually be global and passed to the heatmap calls, and default to `extrema(volume)`.

**Comment by SimonDanisch** [comment]
This looks correct:
image
So I guess it's the z plane that's wrong

**Comment by t-bltg** [comment]
> Where the planes meet, they need to go through the same points in the volume, so they need to have have the same color where they meet... That's quite clearly not happening

It depends on the location though:
ss-1

:thinking:

**Comment by t-bltg** [comment]
> This looks correct:
> image
> So I guess it's the xy plane that's wrong

That seems to fix the issue `hattributes[:colorrange] = plot[:colorrange][]`.

**Comment by SimonDanisch** [comment]
Yeah been there ;) these cos/sin plots are full of symmetries, so there are lots of configurations where they look correct even when wrong!

**Comment by t-bltg** [comment]
> Yeah been there ;) these cos/sin plots are full of symmetries, so there are lots of configurations where they look correct even when wrong!

Harmonic functions are really useful though :wink:

**Comment by t-bltg** [comment]
New output:

sl

**Pull request merged**
