### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by musm**
supersedes https://github.com/JuliaPlots/Makie.jl/pull/197 
(sorry but I wanted to commit my changes to a new branch)

### CODE REVIEW

**Comment by musm** [comment]
@SimonDanisch  this is ready for review

**Comment by SimonDanisch** [comment]
Very cool! Works on windows + linux... Did you, by any chance, run this on osx?

**Comment by musm** [comment]
the GLFW icon function does not do anything on osx, it's only for Windows and Linux

Thanks for the review

**Comment by musm** [comment]
BTW there are other options at https://www.flaticon.com/packs/charts-and-diagrams-14 we could use

I kinda arbitrarily chose which one I thought looked decent.

I future goal could be to expose the icon interface, so users can use their own icons for custom applications.

**Pull request merged**
