### PR TITLE
Add polar plot and scatter recipes

### PR DESCRIPTION
**Pull request by garrekstemo**
# Description

Fixes [# 521](https://github.com/JuliaPlots/Makie.jl/issues/521)

I added two recipes for creating polar plots and scatter polar plots, following the plan posted in issue #521 by @asinghvi17. I understand (from other issues) that there is some inconsistency with how Attributes are used, so I wasn't sure what to do there and mostly followed other recipes. I also would like to remove the xy axes spines and decorations, but I have seen elsewhere that this is under consideration since recipes are apparently older than the Axis framework. I wasn't sure how to handle the docs, and I put the `lines!` plot and `scatter!` plot examples in the same .md file. The plots I include in the docs are attached to this PR.

As far as setting r-ticks and theta-ticks, does my solution look reasonable? I thought this in particular would need to be reviewed.

(This is my first PR (ever!), so please guide me if there's something I'm missing)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Added an entry in NEWS.md (for new features and breaking changes)
- [x] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [x] Added reference image tests for new plotting functions, recipes, visual options, etc.

## Images

`polar(r, theta)`

3polarplots

`polarscatter(r, theta)`
scatterplot

### CODE REVIEW

**Comment by juliohm** [comment]
@garrekstemo any chance you could take this opportunity to also add a polar heatmap? Now that you have the concepts fresh in your mind, maybe it is easy to consider this plot as well?

**Comment by ffreyer** [comment]
I think the way we would want to implement polar plots is by adding a transform function (https://github.com/JuliaPlots/Makie.jl/blob/f04ea93cde4384bad3f008bddf291a15ac35774a/src/layouting/transformation.jl) that converts polar to Cartesian coordinates. That way (r, \theta) inputs would work for any plot that uses that transform. Polar axis should probably be their own separate thing. I.e. we should have something like `PolarAxis` in analog to `Axis` so you can pick the layout you want.

**Comment by garrekstemo** [comment]
OK, that makes a lot more sense and would be more generalizable. I'll close this PR and help out with transform functions where I can.

**Comment by asinghvi17** [comment]
GeoMakie is now just a wrapper around Axis with some conveniences for projections, but does everything else using the Scene transformation interface, specifically `scene.transformation.transform_func` and defining `Makie.apply_transform`.

I have been meaning to make a sort of "NonlinearAxis" `Block` for a while but have been slowly iterating on how it might work and what changes would be desirable in Makie.

As of now it should be easy to simply feed a polar-to-cartesian converter to transform_func and possibly use the framework of this PR to draw gridlines.  The only question then would be the logic of where and how to draw ticks...

**Comment by adigitoleo** [comment]
Thanks for the info, I should have checked more of the GeoMakie source. I'll try with transform_func, since I don't really need ticks for my case ("pole figures" of crystalline texture, [Wikipedia](https://en.wikipedia.org/wiki/Pole_figure), [rust prototype](https://github.com/MFraters/cpo_analyzer)) The contouring might get interesting. I don't expect this kind of plot in particular to be included in Makie core, but drawing the basic axis is similar to a polar plot. If NonlinearAxis is on the table, then I'll also mention  [stereographic plots](https://github.com/joferkington/mplstereonet) in general. I can try to help with all of the above.

**Comment by adigitoleo** [comment]
I've started a thread [over at discourse](https://discourse.julialang.org/t/non-affine-transformations-in-makie/81951) to discuss this. I'm also interested in doing Ternary plots, and can try to help with that as well later.

**Comment by adigitoleo** [comment]
#2014

**Pull request closed without merging**
