### PR TITLE
Fix Axis3D scale

### PR DESCRIPTION
**Pull request by t-bltg**
Partial correction for https://github.com/JuliaPlots/Makie.jl/issues/1142.

Output:
ok

### CODE REVIEW

**Comment by ffreyer** [comment]
Translations and rotations are also broken. More generally it seems like `text(::Vector)` ignores transformations - maybe we can fix it there?

Screenshot from 2021-07-19 11-25-22
Screenshot from 2021-07-19 11-25-51

**Comment by t-bltg** [comment]
@ffreyer, can you share your broken example ? I cannot reproduce this.

**Comment by ffreyer** [comment]
For text:

```julia
fig, ax, p = text(["Test", "Test"], position=[Point3f0(0), Point3f0(1)], space=:data, textsize = 0.1)
translate!(p, 100, 0, 0)
```

For axis:

```julia
translate!(ax.scene, 1, 0, 0)
```

**Comment by t-bltg** [comment]
> Translations and rotations are also broken. More generally it seems like `text(::Vector)` ignores transformations - maybe we can fix it there?

It worked in `0.14.2`, so I'm wondering what caused this change ...

**Comment by SimonDanisch** [comment]
@jkrumbiegel I guess we lost the text translation again? :D

**Comment by SimonDanisch** [comment]
> Translations and rotations are also broken. More generally it seems like `text(::Vector)` ignores transformations - maybe we can fix it there?
 

I think master should have a fix for this:
https://github.com/JuliaPlots/Makie.jl/pull/1147

At least @t-bltg  mwe works now!

**Comment by t-bltg** [comment]
Superseded by https://github.com/JuliaPlots/Makie.jl/pull/1147 (with a minor issue on label position).

**Pull request closed without merging**
