### PR TITLE
Replace f0 type suffix with f and rename Rect types

### PR DESCRIPTION
**Pull request by knuesel**
* Switch to new GeometryBasics type names from https://github.com/JuliaGeometry/GeometryBasics.jl/pull/97
* Rename similar suffixes defined by Makie itself: `Quaternionf0`->`Quaternionf`, `RGBf0`->`RGBf`, `RGBAf0`->`RGBAf`, with deprecation warnings for the old names.

If these changes are OK with you, I'll continue with PRs for MathTeXEngine, Animations, AlgebraOfGraphics and FreeTypeAbstraction.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Oh boi, this PR is of course super sensitive to any other PR getting merged :-O I hope you have a replace regex to run again, instead of running a nasty resolve conflict?

**Comment by knuesel** [comment]
Yes I have a script with regexes :) I'll post it tomorrow morning (don't have access to the computer right now).

**Comment by knuesel** [comment]
I've posted the script in the PR description at https://github.com/JuliaGeometry/GeometryBasics.jl/pull/97.

I'll update this PR whenever another PR is merged, it's no trouble at all.

**Comment by knuesel** [comment]
@SimonDanisch this should be ready now (the relevant dependents have upgraded to GeometryBasics 0.4.1).

**Comment by SimonDanisch** [comment]
I guess this still needs GridLayoutBase to get an upgrade?

**Comment by knuesel** [comment]
It should work with GridLayoutBase 0.6.0 which was released earlier today. I guess it's a registry update/cache issue: the checks that started a few minutes later were successful. Maybe try again?

**Comment by SimonDanisch** [comment]
Replaced by https://github.com/JuliaPlots/Makie.jl/pull/1252

**Pull request closed without merging**
