### PR TITLE
Remove StatsMakie.jl as an export

### LINKED ISSUE #357: Loading Makie invalidates display code
```julia
julia> @time display(1 + 1)
2
  0.000203 seconds (27 allocations: 960 bytes)

julia> using Makie

julia> @time display(1 + 1)
2
  7.101467 seconds (37.97 M allocations: 1.798 GiB, 10.85% gc time)
```

### PR DESCRIPTION
**Pull request by asinghvi17**
to fix #357

### CODE REVIEW

**Comment by asinghvi17** [comment]
```julia
julia> using Makie

julia> @time display(1+1)
2
  0.000095 seconds (29 allocations: 1.094 KiB)
```

**Comment by asinghvi17** [comment]
```julia
julia> @time using Makie
  5.869136 seconds (9.90 M allocations: 579.683 MiB, 5.46% gc time)

julia> @time display(lines(rand(10)))
 47.261599 seconds (132.68 M allocations: 6.523 GiB, 7.18% gc time)
GLMakie.Screen(...)

julia> @time display(lines(rand(10)))
  8.160506 seconds (20.80 M allocations: 1.046 GiB, 5.73% gc time)
GLMakie.Screen(...)

julia> @time display(lines(rand(10)))
  0.179109 seconds (104.30 k allocations: 8.962 MiB)
GLMakie.Screen(...)
```

**Comment by asinghvi17** [comment]
Without these changes:
```julia
julia> @time using Makie
 12.904619 seconds (27.78 M allocations: 1.489 GiB, 4.95% gc time)

julia> @time display(lines(rand(10)))
 48.804432 seconds (133.16 M allocations: 6.563 GiB, 7.45% gc time)
GLMakie.Screen(...)

julia> @time display(lines(rand(10)))
  8.844280 seconds (21.41 M allocations: 1.080 GiB, 5.66% gc time)
GLMakie.Screen(...)

julia> @time display(lines(rand(10)))
  0.187993 seconds (88.16 k allocations: 8.573 MiB)
GLMakie.Screen(...)
```

**Comment by piever** [comment]
I don't quite understand the exact start up time implications, but I think it's OK to not have StatsMakie if this improves startup. We can put it back when it becomes a bit faster to load and is more stable.

**Comment by SimonDanisch** [comment]
Would be much nicer to figure out the cause... But I guess nobody has time for this :D 
Let's merge it, thanks @asinghvi17!

**Pull request merged**
