### PR TITLE
Add docs for remote

### PR DESCRIPTION
**Pull request by SebastianM-C**
Let me know where should I include the new remote docs section and if I should add / change anything.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Beautiful :) I'd just add this as an additional page!

**Comment by SebastianM-C** [comment]
Before the frequently asked questions would be ok?

**Comment by SimonDanisch** [comment]
Sounds good!

**Comment by SimonDanisch** [comment]
Thank you :)

**Pull request merged**
