### PR TITLE
add compile benchmarks

### PR DESCRIPTION
**Pull request by SimonDanisch**
Add some benchmark code to keep track of compile time latencies

### CODE REVIEW

**Comment by SimonDanisch** [comment]
## Compile Times compared to tagged

**Comment by SimonDanisch** [comment]
## Compile Times compared to tagged

**Comment by SimonDanisch** [comment]
## Compile Times compared to tagged 2

**Comment by SimonDanisch** [comment]
## Compile Times compared to tagged 2

**Comment by SimonDanisch** [comment]
test comment

**Comment by SimonDanisch** [comment]
## Compile Times compared to tagged

**Comment by timholy** [comment]
This is lovely work, Simon! Looking forward to seeing those lines go down...and happy to see what looks like progress already.

**Pull request merged**
