### PR TITLE
allow lines of offsetarrays

### PR DESCRIPTION
**Pull request by yakir12**
Super simple tiny change that allows plotting lines of OffsetArrays, suggested by @SimonDanisch on slack. It solves #1259. 

This needs tests (it passes locally), but I'm not sure exactly how to properly test it. My naive approach would be to:
1. add OffsetArrays dependency to the Project file in the test repo
2. add a new test file for OffsetArrays
3. include said file in runtests.jl

Would that be good enough...?

### CODE REVIEW

**Comment by yakir12** [comment]
Not sure what to do with this. My needs to plot offset arrays have changed, but I bet someone will need it at some point. So if there is anything else I can/should do to get this merged let me know.

**Comment by SimonDanisch** [comment]
I see... I think this is mergeable right?

**Comment by yakir12** [comment]
Technically it is mergeable, but while this works for image(some_offsetarray), it does not work for heatmap. So not sure it's in a fantastic state.

**Comment by SimonDanisch** [comment]
Lets merge this... We can polish it later - the offsetarray depedency seems fine, since several packages we depend on already depend on it

**Pull request merged**
